function test_different_smooth_function_greedy_tt_svd
%% a test tensor generated by the sin function
clc;clear;
nn = [40,40,40,40,40];d = length(nn);
% % smooth one
% fun = @(ind) sin(sqrt(sum((ind/39 - 1/39).^2)));
% index = linspace(0, 1, 40);[I1, I2, I3, I4, I5] = ndgrid(index);
% A = sin((I1.^2 + I2.^2 + I3.^2 + I4.^2 + I5.^2).^(1/2));
% % smooth two
% fun = @(ind) 1./(1+sum(ind-1)/39);
% index = linspace(0, 1, 40);[I1, I2, I3, I4, I5] = ndgrid(index);
% A =1./(1 + I1 + I2 + I3 + I4 + I5);
% smooth three
c = rand(1, 5);c = c/sum(c);temp = 185/25;c = c * temp;
fun = @(ind) (1+c(1)*(ind(1)-1)/39+c(2)*(ind(2)-1)/39+c(3)*(ind(3)-1)/39+c(4)*(ind(4)-1)/39+c(5)*(ind(5)-1)/39).^(-6);
index = linspace(0, 1, 40);[I1, I2, I3, I4, I5] = ndgrid(index);
A =(1 + c(1) * I1 + c(2) * I2 + c(3) * I3 + c(4) * I4 + c(5) * I5).^(-6);
normA = norm(A(:));

relerr = [1e-2,1e-3,1e-4,1e-5];
for i = 1 : length(relerr)
    TTr = greedy_tt_svd(A, relerr(i))
end

end