function test_different_real_data_adaptive
%% a test tensor generated by the sin function
clc;clear;format short e
%% yale B
% load('dataYaleB.mat');
% A = X(1 : 451, 1 : 602, 1 : 540);
% A = reshape(A, [41, 42, 43, 44, 45]);
% nn = [41, 42, 43, 44, 45];d = 5;
%% washington
% load('washington.mat');
% A = washington_DC_mall_double_data;
% nn = [35 37 38 39 39];A = A(:);A = A(1 : prod(nn));
% A = reshape(A, nn);d = 5;
%% 
load('coil100A.mat');
load('coil100B.mat');
A(:, :, :, 1 : 50, :) = A1;A(:, :, :, 51 : 100, :) = A2;
A = reshape(A, [64, 64, 50, 72, 24]);nn = [64, 64, 50, 72, 24];d = 5;
normA = norm(A(:));
relerr = 0.01;
% kk = linspace(2, 4, 10);
% for P = 1 : 10
%     P
%     k = kk(P);relerr = 10^(-k);
%     for sample = 1 : 10
%         sample
        
        tic;Q = tt_tensor(A, relerr);T2 = toc;
%         AT2(P, sample) = T2;
%         A2 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
%         A2 = ttt(A2, tensor(Q{3}), [3], [1]);
%         A2 = ttt(A2, tensor(Q{4}), [4], [1]);
%         A2 = ttt(A2, tensor(Q{5}), [5], [1]);A2= double(A2);
        R2 = rank(Q)
        ERR2 = norm(full(Q) - A(:))/normA
%         AERR2(P, sample) = ERR2;
        
        [Q, ~, time] = adaprandomizedTT(A, relerr, 10);T3 = time;
%         AT3(P, sample) = T3;
        A3 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
        A3 = ttt(A3, tensor(Q{3}), [3], [1]);
        A3 = ttt(A3, tensor(Q{4}), [4], [1]);
        A3 = ttt(A3, tensor(Q{5}), [5], [1]);A3 = double(A3);
        Q
        ERR3 = norm(A3(:) - A(:))/normA
%         AERR3(P, sample) = ERR3;
        
        [Q, ~, time] = adaprandomizedTT_kr(A, relerr, 10);T4 = time;
%         AT4(P, sample) = T4;
        A4 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
        A4 = ttt(A4, tensor(Q{3}), [3], [1]);
        A4 = ttt(A4, tensor(Q{4}), [4], [1]);
        A4 = ttt(A4, tensor(Q{5}), [5], [1]);A4 = double(A4);
        Q
        ERR4 = norm(A4(:) - A(:))/normA
%         AERR4(P, sample) = ERR4;
        
        [Q, ~, time] = randomizedTTEI_auto(A, relerr, 10, 0);T5 = time;
%         AT5(P, sample) = T5;
        A5 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
        A5 = ttt(A5, tensor(Q{3}), [3], [1]);
        A5 = ttt(A5, tensor(Q{4}), [4], [1]);
        A5 = ttt(A5, tensor(Q{5}), [5], [1]);A5 = double(A5);
        Q
        ERR5 = norm(A5(:) - A(:))/normA
%         AERR5(P, sample) = ERR5;
        
        [Q, ~, time] = randomizedTTEI_auto_kr(A, relerr, 10, 0);T6 = time;
%         AT6(P, sample) = T6;
        A6 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
        A6 = ttt(A6, tensor(Q{3}), [3], [1]);
        A6 = ttt(A6, tensor(Q{4}), [4], [1]);
        A6 = ttt(A6, tensor(Q{5}), [5], [1]);A6 = double(A6);
        Q
        ERR6 = norm(A6(:) - A(:))/normA
%         AERR6(P, sample) = ERR6;
        
%         [Q, ~, time] = randomizedTTEI_auto(A, relerr, 10, 1);T7 = time;
%         AT7(P, sample) = T7;
%         A7 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
%         A7 = ttt(A7, tensor(Q{3}), [3], [1]);
%         A7 = ttt(A7, tensor(Q{4}), [4], [1]);
%         A7 = ttt(A7, tensor(Q{5}), [5], [1]);A7 = double(A7);
%         AERR7(P, sample) = norm(A7(:) - A(:))/normA;
%         
%         [Q, ~, time] = randomizedTTEI_auto_kr(A, relerr, 10, 1);T8 = time;
%         AT8(P, sample) = T8;
%         A8 = ttt(tensor(Q{1}), tensor(Q{2}), [2], [1]);
%         A8 = ttt(A8, tensor(Q{3}), [3], [1]);
%         A8 = ttt(A8, tensor(Q{4}), [4], [1]);
%         A8 = ttt(A8, tensor(Q{5}), [5], [1]);A8 = double(A8);
%         AERR8(P, sample) = norm(A8(:) - A(:))/normA;
    
%         T9 = tic;T_action =@(xx,k) dense_tensor_action(double(A), xx, k);
%         A9 = tensor_train_from_tensor_action(T_action, nn, 2 * P, relerr, 10);
%         T9 = toc(T9)
%         AT9(P, sample) = T9;
%         A9 = build_dense_tensor_from_tensor_train(A9);
%         AERR9(P, sample) = norm(A9(:) - A(:))/normA;
%     end
% end
% sample = 10;
% figure(1)
% subplot(121)
% plot(kk, sum(AERR1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % plot(kk, sum(AERR9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AERR8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
% subplot(122)
% plot(kk, sum(AT1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % plot(kk, sum(AT9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
% figure(2)
% subplot(121)
% semilogy(kk, sum(AERR1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % semilogy(kk, sum(AERR9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
% subplot(122)
% plot(kk, sum(AT1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % plot(kk, sum(AT9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% plot(kk, sum(AT8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
% figure(3)
% subplot(121)
% semilogy(kk, sum(AERR1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % semilogy(kk, sum(AERR9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AERR8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
% subplot(122)
% semilogy(kk, sum(AT1, 2)/sample, '-+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT2, 2)/sample, '-o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% % semilogy(kk, sum(AT9, 2)/sample, '-d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT3, 2)/sample, ':*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT4, 2)/sample, ':+', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT5, 2)/sample, '--o', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT6, 2)/sample, '--d', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT7, 2)/sample, '-.*', 'LineWidth', 2, 'MarkerSize', 10);hold on
% semilogy(kk, sum(AT8, 2)/sample, '-.s', 'LineWidth', 2, 'MarkerSize', 10);hold on
end